"""device-routine-timings table

Revision ID: e53bc9e9bf68
Revises: 
Create Date: 2020-09-19 22:29:16.705488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53bc9e9bf68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('devType', sa.String(length=16), nullable=True),
    sa.Column('interface1', sa.Integer(), nullable=True),
    sa.Column('interface2', sa.Integer(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('startTime', sa.Integer(), nullable=True),
    sa.Column('stopTime', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timing')
    op.drop_table('device')
    op.drop_table('routine')
    # ### end Alembic commands ###
